["```py\n    import unittest\n    from fibo import fibonacci\n\n    class Test(unittest.TestCase):\n\n        def test_fibo(self):\n            result = fibonacci(4)\n            self.assertEqual(result, 3)\n\n    if __name__ == '__main__':\n        unittest.main()\n```", "```py\n1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n```", "```py\n \u03bb python3 -m venv .env\n  source .env/bin/activate\n F\n ======================================================================\n FAIL: test_fibo (__main__.Test)\n ----------------------------------------------------------------------\n Traceback (most recent call last):\n File \"test_fibo.py\", line 8, in test_fibo\n self.assertEqual(result, 3)\n AssertionError: 5 != 3\n\n ----------------------------------------------------------------------\n Ran 1 test in 0.000s\n\n FAILED (failures=1)\n```", "```py\n\n    \u03bb python test_fibo.py\n .\n ----------------------------------------------------------------------\n Ran 1 test in 0.000s\n\n OK\n```", "```py\n    from fibo import fibonacci\n\n    def test_fibo():\n        assert fibonacci(4) == 3\n```", "```py\n \u03bb pytest test_fibo2.py -q\n F                                                              [100%]\n ============================= FAILURES ==============================\n _____________________________ test_fibo _____________________________\n\n def test_fibo():\n >       assert fibonacci(4) == 3\n E       assert 5 == 3\n E        + where 5 = fibonacci(4)\n\n test_fibo2.py:4: AssertionError\n 1 failed in 0.03 seconds\n```"]